apiVersion: v1
kind: ConfigMap
metadata:
  name: application-configs
  namespace: default
data:
  app.value: "45000"
  app.type: test-application
  app.ui: web

## user in deployment yaml as  belopw
##env:
#        - name: APPLICATION_TYPE
#          valueFrom:
#            configMapKeyRef:
#              name: application-configs
#              key: app.type
